/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AccessControlTestHelperInterface extends ethers.utils.Interface {
  functions: {
    "readGetAnswer(address,uint256)": FunctionFragment;
    "readGetRoundData(address,uint80)": FunctionFragment;
    "readGetTimestamp(address,uint256)": FunctionFragment;
    "readLatestAnswer(address)": FunctionFragment;
    "readLatestRound(address)": FunctionFragment;
    "readLatestRoundData(address)": FunctionFragment;
    "readLatestTimestamp(address)": FunctionFragment;
    "testLatestTransmissionDetails(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "readGetAnswer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readGetRoundData",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readGetTimestamp",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readLatestAnswer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "readLatestRound",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "readLatestRoundData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "readLatestTimestamp",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "testLatestTransmissionDetails",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "readGetAnswer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readGetRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readGetTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readLatestAnswer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readLatestRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readLatestRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readLatestTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testLatestTransmissionDetails",
    data: BytesLike
  ): Result;

  events: {
    "Dummy()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Dummy"): EventFragment;
}

export type DummyEvent = TypedEvent<[] & {}>;

export class AccessControlTestHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AccessControlTestHelperInterface;

  functions: {
    readGetAnswer(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    readGetRoundData(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    readGetTimestamp(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    readLatestAnswer(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    readLatestRound(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    readLatestRoundData(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    readLatestTimestamp(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testLatestTransmissionDetails(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  readGetAnswer(
    _aggregator: string,
    _roundID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  readGetRoundData(
    _aggregator: string,
    _roundID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  readGetTimestamp(
    _aggregator: string,
    _roundID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  readLatestAnswer(
    _aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  readLatestRound(
    _aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  readLatestRoundData(
    _aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  readLatestTimestamp(
    _aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testLatestTransmissionDetails(
    _aggregator: string,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    readGetAnswer(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    readGetRoundData(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    readGetTimestamp(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    readLatestAnswer(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    readLatestRound(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    readLatestRoundData(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    readLatestTimestamp(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    testLatestTransmissionDetails(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Dummy()"(): TypedEventFilter<[], {}>;

    Dummy(): TypedEventFilter<[], {}>;
  };

  estimateGas: {
    readGetAnswer(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    readGetRoundData(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    readGetTimestamp(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    readLatestAnswer(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    readLatestRound(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    readLatestRoundData(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    readLatestTimestamp(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testLatestTransmissionDetails(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    readGetAnswer(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    readGetRoundData(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    readGetTimestamp(
      _aggregator: string,
      _roundID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    readLatestAnswer(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    readLatestRound(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    readLatestRoundData(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    readLatestTimestamp(
      _aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testLatestTransmissionDetails(
      _aggregator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
