/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AggregatorValidatorInterface,
  AggregatorValidatorInterfaceInterface,
} from "../AggregatorValidatorInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "previousRoundId",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "previousAnswer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "currentRoundId",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "currentAnswer",
        type: "int256",
      },
    ],
    name: "validate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AggregatorValidatorInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AggregatorValidatorInterfaceInterface {
    return new utils.Interface(_abi) as AggregatorValidatorInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AggregatorValidatorInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AggregatorValidatorInterface;
  }
}
